/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class done_ClockOutput */

#ifndef _Included_done_ClockOutput
#define _Included_done_ClockOutput
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     done_ClockOutput
 * Method:    setupWindow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_done_ClockOutput_setupWindow
  (JNIEnv *, jclass);

/*
 * Class:     done_ClockOutput
 * Method:    doAlarm
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_done_ClockOutput_doAlarm
  (JNIEnv *, jclass);

/*
 * Class:     done_ClockOutput
 * Method:    showTime
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_done_ClockOutput_showTime
  (JNIEnv *, jclass, jint);

/*
 * Class:     done_ClockOutput
 * Method:    diagnostics
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_done_ClockOutput_diagnostics
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
