/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class done_InputSampler */

#ifndef _Included_done_InputSampler
#define _Included_done_InputSampler
#ifdef __cplusplus
extern "C" {
#endif
#undef done_InputSampler_MIN_PRIORITY
#define done_InputSampler_MIN_PRIORITY 1L
#undef done_InputSampler_NORM_PRIORITY
#define done_InputSampler_NORM_PRIORITY 5L
#undef done_InputSampler_MAX_PRIORITY
#define done_InputSampler_MAX_PRIORITY 10L
/*
 * Class:     done_InputSampler
 * Method:    haveInput
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_done_InputSampler_haveInput
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
