/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class done_ClockInput */

#ifndef _Included_done_ClockInput
#define _Included_done_ClockInput
#ifdef __cplusplus
extern "C" {
#endif
#undef done_ClockInput_SHOW_TIME
#define done_ClockInput_SHOW_TIME 0L
#undef done_ClockInput_SET_ALARM
#define done_ClockInput_SET_ALARM 1L
#undef done_ClockInput_SET_TIME
#define done_ClockInput_SET_TIME 2L
/*
 * Class:     done_ClockInput
 * Method:    getAlarmFlag
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_done_ClockInput_getAlarmFlag
  (JNIEnv *, jclass);

/*
 * Class:     done_ClockInput
 * Method:    getChoice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_done_ClockInput_getChoice
  (JNIEnv *, jclass);

/*
 * Class:     done_ClockInput
 * Method:    getValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_done_ClockInput_getValue
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
